version: '5.0'

actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset analysis/dm_reg_dataset_Irene.py
      --test-data-file analysis/test_dm_reg_dataset_Irene.py
      --output output/dataset.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dataset.csv.gz
