version: '5.0'

#to run in terminal: opensafely exec
actions:
  generate_dataset:
    run: >
      ehrql:v1 generate-dataset analysis/dm_reg_dataset_Irene.py
      --test-data-file analysis/test_dm_reg_dataset_Irene.py
      --output output/dm_reg_dataset_Irene.csv.gz
    outputs:
      highly_sensitive:
        dataset: output/dm_reg_dataset_Irene.csv.gz

  generate_dm017_measures:
    run: >
      ehrql:v1 generate-measures analysis/dm_reg_measures_Irene.py
      --output output/dm017/:csv
    outputs:
      moderately_sensitive:
        measure: output/dm017/*.csv

  visualise_dm017_measures:
    run: >
      r:v2 analysis/visualise_measures_Irene.R
    needs: [generate_dm017_measures]
    outputs:
      moderately_sensitive:
        measure: output/figures/*.png